### ISSUE TITLE
GEAS to report on invalid `minimum_otp_vsn` if in rebar3 project

### ISSUE THREAD

**Issue by kivra-pauoli** [crownedgrouse/geas#10]
Would you be interested in having `geas` report on an incorrect `minimum_otp_vsn` in the scope of a `rebar3` project?

What could be done?

* get that config. key from `rebar.config`
* compare to `geas`' calculated release window
* potentially report an error

## Motivation

When I saw `===> Current Erlang/OTP release is incompatible with project release window` I thought this was what `geas` was complaining about, but after I commented out that option in `rebar.config` I understood "Current Erlang/OTP release" is "The Erlang/OTP release used for the analysis".

Maybe we could add the calculated release value to the error message?

**Comment by crownedgrouse** [comment]
Yes, sure, but I would prefer this to be implemented in https://github.com/crownedgrouse/geas_rebar3 plugin .
Closing the ticket, but your PR welcome in geas_rebar3 project !

**Comment by kivra-pauoli** [comment]
Could you maybe move the issue there? Thanks.
