### ISSUE TITLE
Compilation error in Erlang 27

### ISSUE THREAD

**Issue by arcusfelis** [crownedgrouse/geas#15]
`maybe` is a reserved word now, and should be escaped like `'maybe'`:
```
rel_info({tls_handshake_1_3,maybe,0}) -> {"24.0", "25.3", ">=24.0 <=25.3", true};
```

**Comment by crownedgrouse** [comment]
Thanks for having reported this. I will fix in next release.

**Comment by crownedgrouse** [comment]
Geas  2.8.1 is now released and atom was correctly escaped by OTP-27 while releasing.
But this imply that when using OTP-27, older Geas releases are not compatible, but this is not recommended to use an OTP release with a Geas version not aware of it.
Thank for the head up !
Closing
