### ISSUE TITLE
Complete support of source files

### ISSUE THREAD

**Issue by fenollp** [crownedgrouse/geas#2]
If we don't know which OTP release a project will compile with, how will we be able to run Geas? As of now it only runs on compiled projects!

Please add support for source files (erlang at least). 
Once support is ready, we can add Geas output to other.erldocs.com. There's an issue there already https://github.com/erldocs/other.erldocs.com/issues/88

**Comment by crownedgrouse** [comment]
Yes, actually geas is to be used on own projects and dependencies , so generally,  compilation is ok and geas usefull to know on what other release the global project can run, mainly due to dependancies contraints.
A source mode is usefull for the reason you gave, mainly when using geas on a large bunch of external projects. 
I will look into this !

**Comment by crownedgrouse** [comment]
Note, you can run geas, let say with 17.5 , and be able to know if a project can run on 18.2 if the geas database is uptodate. 
But the need is to know what release is needed to compile.

**Comment by crownedgrouse** [comment]
my last commit allow to check source files if environment variable GEAS_USE_SRC=1 is set. 
(unset or GEAS_USE_SRC=0 to go back to default).
Your feedback welcome.

**Comment by fenollp** [comment]
Looking forward to it! How can I use geas on a non rebar/erlang.mk project with `GEAS_USE_SRC=1` set?

**Comment by crownedgrouse** [comment]
Geas do not care of build system. It analyze only. app or .app.src,  Beam files or erl files, depending env variable.

**Comment by crownedgrouse** [comment]
By using geas:info() in a shell, or an escript

**Comment by crownedgrouse** [comment]
Need only a path to root directory

**Comment by fenollp** [comment]
Nice! Could you update the README? I'll close the issue afterwards :)

**Comment by crownedgrouse** [comment]
you may not have seen it, but the readme was updated tonight. does it fit to you ?
