### ISSUE TITLE
Auto imported functions from the erlang module not detected

### ISSUE THREAD

**Issue by eproxus** [crownedgrouse/geas#4]
I'm using the `master` version of the Rebar 3 plugin, and Geas does not detect the usage of auto imported functions from the `erlang` module, e.g. `binary_to_integer/2` or `integer_to_binary/2`.

If I add the `erlang:...` prefix it works.

Let me know if you need any more info.

**Comment by crownedgrouse** [comment]
indeed a bug !  I need to add a test on this because I almost never call imported function without erlang: prefix. good catch.

**Comment by crownedgrouse** [comment]
Please check last  master commit https://github.com/crownedgrouse/geas/commit/55a4b66cb8b2c15255b7b20f0a9ffbb15b6c1fa6  . This should be fixed ! Thanks a lot for this feedback.

**Comment by eproxus** [comment]
Works! Thanks for the quick turnaround time 😄 

Didn't check, but have a hunch that if you override a function with the same name as a built-in function you might get the warning anyway?

**Comment by crownedgrouse** [comment]
if you create a local function called the same than a buit-in , you cannot call it without module prefix, or erlc raise an error with name clash. Did you mean that ?

**Comment by eproxus** [comment]
You can do it,  but you get a warning. If you use for example `-compile({no_auto_import,[binary_to_integer/2]}).` the warning will go away. It also looks like Geas doesn't warn in this case, so ignore my previous comment. 😊

**Comment by crownedgrouse** [comment]
Geas handle only known modules in Erlang releases, so local function should be not considered, normally.
Can we close the issue ?

**Comment by eproxus** [comment]
Thanks for the fix!

**Comment by crownedgrouse** [comment]
Thanks for the report !
