### ISSUE TITLE
trim_all option is not available in 17.5 for binary:split

### ISSUE THREAD

**Issue by crownedgrouse** [crownedgrouse/geas#6]
See https://github.com/crownedgrouse/geas_rebar3/issues/7

**Comment by crownedgrouse** [comment]
was added in 18.0

OTP-12301  Add 'trim_all' option to binary:split/3

	      This option can be set to remove _ALL_ empty parts of the
	      result of a call to binary:split/3.

**Comment by crownedgrouse** [comment]
please upgrade to geas  2.4.1 on hex. thanks to confirm it works. ok on my side with 17.5 and 21.2

**Comment by markusfeyh** [comment]
Wow! thanks for addressing this so efficiently crownedgrouse.

**Comment by crownedgrouse** [comment]
Can I close? BTW using 17.5 is quite old :)

**Comment by markusfeyh** [comment]
Yah, please close. I think geas will be a great tool for figuring out how old something is, including its dependencies. Will ping you if I notice anything else, thank you 👍

**Comment by crownedgrouse** [comment]
Add a little star to the project if you like it ;>)
Closing thanks!
